## CONFIGURATION
node_env: "prod"
ip: 0.0.0.0
port: 4000
# CHANGE IF RUNNING TWO NODES IN SAME MACHINE!
external_port: 81
proxy_port: 8080

## GATEWAY
#### Replace GTW_HOST by localhost if local mode
gtw_host: "http://gateway"
gtw_port: 8181
gtw_timeout: 10000

#### Add your credentials below, obtain them in the Neighbourhood Manager
gtw_id: <your_gtw_id>
gtw_pwd: <your_gtw_pwd>

## Persistance
#### Replace DB_HOST by localhost if local mode
db_type:  'REDIS'
db_password: <your_db_password>
db_host: cache-db
db_port: 6379
db_cache_enabled: "true"
db_cache_ttl: 60

## WoT repository
wot_enabled: "true"
wot_host: "http://wothive"
wot_port: 9000

#### Modes ["dummy", "proxy"(default), "semantic"]
adapter_mode: "semantic"
adapter_host: "<your_adapter_host>"
adapter_port: 443

### triplestore
triplestore_port: 3030

## helio
helio_port: 4567

## ingressroute
node_ingress_path: "/node"
helio_ingress_path: "/helio"
host_path: host.from.your.org
node_path: node.from.your.org

# for dockerhub login
# https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
imageCredentials: 
  registry: quay.io
  username: someone
  password: sillyness
  email: someone@host.com