## CONFIGURATION
node_env: "production"
ip: 0.0.0.0
port: 4000

# CHANGE IF RUNNING TWO NODES IN SAME MACHINE!
external_port: 81
proxy_port: 8080


## GATEWAY
#### Replace GTW_HOST by localhost if local mode
gtw_host: "http://gateway"
gtw_port: 8181
gtw_timeout: 10000

#### Add your credentials below, obtain them in the Neighbourhood Manager
<<<<<<< HEAD
gtw_id: "9da133f2-211a-4d85-81b5-df319cc1a184"
gtw_pwd: "montsenynode"
=======
gtw_id: "b877d363-8d4f-4ba6-b408-92f5d4354b7b"
gtw_pwd: "mapnode"
>>>>>>> 69c8107efad9f31459b51608f0a8f923bc910a39

## Persistance
#### Replace DB_HOST by localhost if local mode
db_type:  'REDIS'
db_password: ''
db_host: cache-db
db_port: 6379
db_cache_enabled: "true" #"true"
db_cache_ttl: 60

## WoT repository
wot_enabled: "true"
wot_host: "http://wothive"
wot_port: 9000

#### Modes ["dummy", "proxy"(default), "semantic"]
adapter_mode: "semantic"
<<<<<<< HEAD
adapter_host: "https://agent.montseny.aiguasol.coop/" #"<your_adapter_host>"
=======
adapter_host: "https://agent.map.aiguasol.coop/" #"<your_adapter_host>"
>>>>>>> 69c8107efad9f31459b51608f0a8f923bc910a39
adapter_port: 443 #3001
use_mapping: "true"

semantic_odrl_enabled: "false"
semantic_shacl_enabled: "false"
xmpp_environment: "auroral"
xmpp_service: "xmpp://xmpp.auroral.bavenir.eu:5222"
xmpp_domain: "xmpp.auroral.bavenir.eu"
xmpp_resource: AuroralNode

### gateway
nm_host: "https://auroral.bavenir.eu/api/gtw/v1/"
gtw_token_ttl: 86400
gtw_agent_host: http://auroral-agent
gtw_agent_port: 4000
gtw_agent_timeout: 10000
event_settings_file: persistance/events.json

### triplestore
triplestore_port: 3030

## helio
helio_port: 4567

## front end helio
fe_helio_mode: 'APP'
<<<<<<< HEAD
fe_helio_host: https://montseny.aiguasol.coop/helio #http://helio:4567
=======
fe_helio_host: https://map.aiguasol.coop/helio #http://helio:4567
>>>>>>> 69c8107efad9f31459b51608f0a8f923bc910a39
fe_helio_port: 4202
fe_helio_ext_port: 80

## ingress
<<<<<<< HEAD
node_path: montseny.aiguasol.coop
agent_path: agent.montseny.aiguasol.coop
=======
node_path: map.aiguasol.coop
agent_path: agent.map.aiguasol.coop
>>>>>>> 69c8107efad9f31459b51608f0a8f923bc910a39
proxy_ingress_path: "/docs"
helio_ingress_path: "/helio"
fe_helio_ingres_path: "/fehelio"

# for dockerhub login
# https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets
imageCredentials: 
  registry:
    auth: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXbG5kV0Z6YjJ3NlFXbG5kV0Z6YjJ3NU1XZG9NVFk9IgoJCX0KCX0KfQ==