apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: {{ .Values.fe_helio_port | quote }}
      port: {{ .Values.fe_helio_port }}
      targetPort: {{ .Values.fe_helio_ext_port }}
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
